category_mapping = {
    "food_organics": "Is_Food_enabled = 1",
    "cardboard": "Is_Cardboard_enabled = 1",
    "glass": "Is_Glass_enabled = 1",
    "metal":"Is_Metal_enabled = 1",
    "paper": "Is_Paper_enabled = 1",
    "plastic": "Is_Plastic_enabled = 1",
    "textile_trash": "Is_Textile_enabled=1",
    "vegetation":"Is_Vegetation_enabled =1",
    "miscellaneous_trash":"Is_Miscellanous_Trash_enabled =1",
    "mirror":"Is_Glass_enabled = 1",# TO be changed
    "car_battery":"Is_Miscellanous_Trash_enabled =1",# TO be changed
    "neon":"Is_Neon_enabled=1",
    "pharmacy":"Is_Pharmacy_enabled=1",
    "tire":"Is_Tire_enabled=1",
    "printer_cartridge":"Is_Cartridge_enabled=1",
    "wood":"Is_Miscellanous_Trash_enabled =1", # TO be changed
    "ressourcerie":"Is_Ressourcerie_enabled=1",
    "light_bulb":"Is_Lamp_Light_enabled=1",
    "battery":"Is_Lamp_Light_enabled=1"     # TO be changed
}
